[deps]
ABCConformal = "6a06312b-1f35-42d8-b2e0-a51b61531d54"
Accessors = "7d9f7c33-5ae7-4f3b-8dc6-eff91059b697"
ConcreteDropoutLayer = "cefad46e-21aa-447d-abc5-91039c0799ef"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataFramesMeta = "1313f7d8-7da2-5740-9ea0-a2ca25f37964"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
Lux = "b2108857-7c20-44ae-9111-449ecde12c47"
LuxCUDA = "d0bbae9a-e099-4d5b-a835-1c6931763bda"
MLUtils = "f1d291b0-491e-4a28-83b9-f70985020b54"
Optimisers = "3bd65402-5787-11e9-1adc-39752487f4e2"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StatsPlots = "f3b207a7-027a-5e70-b257-86293d7955fd"
ToeplitzMatrices = "c751599d-da0a-543b-9d20-d0a503d91d24"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"
